### ISSUE TITLE
Java exception on ubuntu system

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/NYU-Bobst-Library-Reservation-Automator-Java#2]
Stack trace:
Exception in thread "main" java.util.NoSuchElementException
    at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
    at nyu.yao.automator.UserPool.createPool(UserPool.java:96)
    at nyu.yao.automator.Automator.createUsers(Automator.java:218)
    at nyu.yao.automator.Automator.setup(Automator.java:51)
    at nyu.yao.automator.Automator.main(Automator.java:39)

Thoughts: update userLogin.csv.example, and update the actual version as well.

**Comment by JasonYao** [comment]
Fixed as of ad075fd9317cd7d568a4593bd616d925ac25463e, requires testing to confirm

**Comment by JasonYao** [comment]
Testing complete and working, revamped all instructions as of 3cad8d72b920812206b76fe0816c523e65fe17e0, and the userLogins.csv.example file has been altered to the correct v2.1.x syntax
