### ISSUE TITLE
No element found exception handling

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/NYU-Bobst-Library-Reservation-Automator-Java#8]
Clean up the following with error handling
`
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 154 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: cf8aa2a9-2fbf-4c17-8f5f-0939a294d269
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous1156340606759719167webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous1156340606759719167webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous1156340606759719167webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous1156340606759719167webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous1156340606759719167webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: User ss6836 had invalid login credentials
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 222 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 0ef14660-98cd-4a70-9d92-c4b16dac2128
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous9001730657310535608webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous9001730657310535608webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous9001730657310535608webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous9001730657310535608webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous9001730657310535608webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 152 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: ce0d3d0d-252f-4e73-af4d-325942452732
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous2761694711464536546webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous2761694711464536546webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous2761694711464536546webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous2761694711464536546webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous2761694711464536546webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 151 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 46be8314-e29f-45f5-bccd-a11511718e40
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous1848426169278335688webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous1848426169278335688webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous1848426169278335688webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous1848426169278335688webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous1848426169278335688webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: User Jst365 had invalid login credentials
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 134 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7a5596c3-6b20-4563-9798-47bf88feef93
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous5817195178345821647webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous5817195178345821647webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous5817195178345821647webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous5817195178345821647webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous5817195178345821647webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 136 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9db3cd03-3ebb-4f80-8dd1-d56fd26dc41f
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor20.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous1905504467377216806webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous1905504467377216806webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous1905504467377216806webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous1905504467377216806webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous1905504467377216806webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)
Error: User aac499 had invalid login credentials
Error: User mns364 had invalid login credentials
Error: User mrd401 had invalid login credentials
Error: User cdc431 had invalid login credentials
Error: Shit, something's on fire
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
Command duration or timeout: 135 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.5.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3671ee5f-5a1a-444d-a160-987fe4df97a2
*** Element info: {Using=xpath, value=//button[@class='btn btn-lg btn-primary']}
    at sun.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
    at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
    at nyu.yao.automator.RunAutomator.selectRoom(RunAutomator.java:260)
    at nyu.yao.automator.RunAutomator.run(RunAutomator.java:57)
    at nyu.yao.automator.Automator.runAutomator(Automator.java:252)
    at nyu.yao.automator.Automator.runAndCleanup(Automator.java:61)
    at nyu.yao.automator.Automator.main(Automator.java:40)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//button[@class='btn btn-lg btn-primary']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jasonpi', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.1.13-v7+', java.version: '1.8.0'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous931845264952866386webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous931845264952866386webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous931845264952866386webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous931845264952866386webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous931845264952866386webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)`

**Comment by JasonYao** [comment]
Fixed as of v2.2.1: e9cc59701fc791d6927313eaa6cf7fdc93265c05
